&lt;?php

/* Protection against direct call */
if (!defined('FORPOST_VALID')) {
    header('HTTP/1.1 404 Not Found', 404);
    header('X-Powered-By: PHP', true);
    die("<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL " . htmlentities($_SERVER['REQUEST_URI'], ENT_QUOTES) . " was not found on this server.</p>\n</body></html>");
}

class <?=ucfirst($controller_name).'Controller'?> extends WebController
{
    /* Uncomment this method if you want to initialize something before other methods will be executed
    public function init()
    {
    }
    */

    public function actionIndex($params)
    {
        $content = 'This is content generated by method "' . __METHOD__ . '" of controller "' . __CLASS__ . '"<br />';
        $content .= 'Edit file <strong>' . __FILE__ . '</strong> to change this message.';
        return Response::content($content);
    }

    /* Uncomment this method if you want to have "catch-all" method
    public function defaultAction($params)
    {
    }
    */
}
