#!/bin/sh

###############################################################
#                                                             #
# @author: Dmitriy Yuriev <coolkid00@gmail.com>               #
# @product: Forpost3                                          #
# @version: 3.1                                               #
# @release date: 04.05.2014                                   #
# @development started: 21.08.2013                            #
# @license: GNU AGPLv3 <http://www.gnu.org/licenses/agpl.txt> #
#                                                             #
# Forpost3 CLI utility.                                       #
#                                                             #
###############################################################

/usr/bin/env php index.php fortress $@
